import { useMemo, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { isAdminAuthenticated, loginAdmin, logoutAdmin } from '../data/adminAuth'
import { rateCardRepository } from '../data/rateCardRepository'
import { calculateQuote } from '../data/quoteCalculator'
import { formatInrRange } from '../data/currency'

const tabs = ['rate cards', 'pricing rules', 'locations', 'finish levels', 'add-ons', 'templates', 'preview']
const inputClass = 'w-full rounded-md border border-line bg-white px-3 py-2.5 text-sm text-ink outline-none transition focus:border-gold focus:ring-2 focus:ring-gold/20'
const buttonClass = 'rounded-md bg-gold px-4 py-2.5 text-xs font-bold uppercase tracking-[0.1em] text-ink transition hover:bg-[#f5d457] focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-gold'
const Field = ({ label, children }) => <label className="flex min-w-0 flex-col gap-1.5 text-sm font-medium text-ink"><span>{label}</span>{children}</label>
const ListText = ({ value = [], onChange, label }) => <Field label={label}><input className={inputClass} value={value.join(', ')} onChange={(event) => onChange(event.target.value.split(',').map((item) => item.trim()).filter(Boolean))} placeholder="Separate items with commas" /></Field>
const EditHint = () => <p className="mt-5 rounded-md border border-gold/40 bg-white px-4 py-3 text-sm text-muted">Create a draft from the Rate cards tab to make changes. The published version stays protected.</p>

function Admin() {
  const navigate = useNavigate()
  const [authenticated, setAuthenticated] = useState(isAdminAuthenticated())
  const [password, setPassword] = useState('')
  const [tab, setTab] = useState('rate cards')
  const [store, setStore] = useState(() => rateCardRepository.getStore())
  const [message, setMessage] = useState('')
  const published = store.rateCards.find((card) => card.status === 'published')
  const draft = store.rateCards.find((card) => card.status === 'draft')
  const editorCard = draft || published
  const refresh = () => setStore(rateCardRepository.getStore())
  const error = (exception) => setMessage(exception?.message || 'Please review the values and try again.')
  const handleLogin = (event) => { event.preventDefault(); if (loginAdmin(password)) { setAuthenticated(true); setPassword(''); setMessage('') } else setMessage('Incorrect password.') }
  const createDraft = () => { try { rateCardRepository.createDraftFromPublished(); refresh(); setMessage('A new draft is ready to edit. Customers still see the published rates.') } catch (exception) { error(exception) } }
  const updateDraft = (transform, successMessage = 'Draft saved.') => { try { const current = rateCardRepository.getStore().rateCards.find((card) => card.status === 'draft'); if (!current) throw new Error('Create a draft before editing prices.'); rateCardRepository.saveRateCard(transform(current)); refresh(); setMessage(successMessage) } catch (exception) { error(exception) } }
  const publish = () => { try { if (!draft) throw new Error('Create and review a draft before publishing.'); rateCardRepository.publishRateCard(draft.id); refresh(); setMessage('Rate card published. New customer quotes will use this version.') } catch (exception) { error(exception) } }
  if (!authenticated) return <main className="min-h-screen bg-paper px-4 py-16 font-sans text-ink sm:px-6 sm:py-24"><div className="mx-auto max-w-md rounded-lg border border-line bg-white p-6 shadow-sm sm:p-8"><p className="mb-3 text-xs font-bold uppercase tracking-[0.2em] text-gold">Protected admin</p><h1 className="font-serif text-4xl">Pricing control room</h1><p className="mt-3 text-sm leading-6 text-muted">Sign in to manage rate cards and customer-facing quote settings.</p><form className="mt-8 flex flex-col gap-4" onSubmit={handleLogin}><Field label="Admin password"><input className={inputClass} type="password" autoComplete="current-password" value={password} onChange={(event) => setPassword(event.target.value)} /></Field><button className={buttonClass} type="submit">Sign in</button></form>{message && <p className="mt-4 text-sm text-red-700" role="alert">{message}</p>}</div></main>
  return <main className="min-h-screen bg-paper px-4 py-8 font-sans text-ink sm:px-6 sm:py-12"><div className="mx-auto max-w-6xl"><header className="flex flex-col gap-5 border-b border-line pb-7 sm:flex-row sm:items-end sm:justify-between"><div><p className="mb-3 text-xs font-bold uppercase tracking-[0.2em] text-gold">Protected admin</p><h1 className="font-serif text-4xl sm:text-5xl">Pricing control room</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-muted">Edit a draft, preview it, then publish when it is ready. Published rates are never changed in place.</p></div><div className="flex flex-wrap gap-3"><button className="rounded-md border border-line px-4 py-2 text-sm transition hover:border-gold" type="button" onClick={() => navigate('/')}>View website</button><button className="rounded-md border border-line px-4 py-2 text-sm transition hover:border-gold" type="button" onClick={() => { logoutAdmin(); setAuthenticated(false) }}>Sign out</button></div></header><nav className="-mx-4 mt-6 flex gap-2 overflow-x-auto border-b border-line px-4 pb-3 sm:mx-0 sm:px-0" aria-label="Pricing controls">{tabs.map((item) => <button className={`shrink-0 rounded-md px-3 py-2 text-xs font-bold uppercase tracking-[0.08em] ${tab === item ? 'bg-gold text-ink' : 'text-muted hover:bg-white'}`} type="button" key={item} onClick={() => setTab(item)}>{item}</button>)}</nav>{message && <p className="mt-5 rounded-md border border-gold/40 bg-white px-4 py-3 text-sm text-ink" role="status">{message}</p>}
    {tab === 'rate cards' && <RateCards published={published} draft={draft} onCreate={createDraft} onPublish={publish} />}
    {tab === 'pricing rules' && <RulesEditor card={editorCard} editable={Boolean(draft)} onUpdate={updateDraft} />}
    {tab === 'locations' && <SimpleEditor type="zone" card={editorCard} editable={Boolean(draft)} onUpdate={updateDraft} />}
    {tab === 'finish levels' && <SimpleEditor type="finish" card={editorCard} editable={Boolean(draft)} onUpdate={updateDraft} />}
    {tab === 'add-ons' && <AddonsEditor card={editorCard} editable={Boolean(draft)} onUpdate={updateDraft} />}
    {tab === 'templates' && <TemplatesEditor templates={store.templates} onSave={(templates) => { rateCardRepository.saveTemplates(templates); refresh(); setMessage('Customer quote templates saved.') }} />}
    {tab === 'preview' && <Preview card={editorCard} isDraft={Boolean(draft)} />}
  </div></main>
}

const RateCards = ({ published, draft, onCreate, onPublish }) => <section className="mt-8"><div className="flex flex-col gap-5 rounded-lg border border-line bg-white p-5 sm:flex-row sm:items-center sm:justify-between sm:p-6"><div><h2 className="text-2xl font-medium">Rate-card versions</h2><p className="mt-2 text-sm text-muted">{draft ? 'You have a draft in progress. Review it in each tab before publishing.' : 'Start a draft to make pricing changes safely.'}</p></div>{draft ? <button className={buttonClass} type="button" onClick={onPublish}>Publish draft</button> : <button className={buttonClass} type="button" onClick={onCreate}>Create a draft</button>}</div><div className="mt-6 grid gap-4 md:grid-cols-2"><VersionCard label="Currently published" card={published} /><VersionCard label="Draft in progress" card={draft} /></div></section>
const VersionCard = ({ label, card }) => <article className="rounded-lg border border-line bg-white p-5"><p className="text-xs font-bold uppercase tracking-[0.14em] text-gold">{label}</p>{card ? <><h3 className="mt-3 text-lg font-medium">{card.version}</h3><p className="mt-2 text-sm text-muted">{card.rules.length} pricing rules · {card.zones.length} locations · {card.finishes.length} finish levels · {card.addons.length} add-ons</p></> : <p className="mt-3 text-sm text-muted">No draft created yet.</p>}</article>

function RulesEditor({ card, editable, onUpdate }) {
  if (!card) return <EditHint />
  const saveRule = (nextRule) => onUpdate((draft) => ({ ...draft, rules: draft.rules.map((rule) => rule.id === nextRule.id ? nextRule : rule) }), 'Pricing rule updated.')
  const addRule = () => onUpdate((draft) => ({ ...draft, rules: [...draft.rules, { id: `rule-${Date.now()}`, projectCategory: 'New construction from scratch', propertyType: 'personal', zoneId: draft.zones[0]?.id, finishLevelId: draft.finishes[0]?.id, minAreaSqFt: 100001, maxAreaSqFt: 200000, lowRatePaisePerSqFt: 100000, highRatePaisePerSqFt: 120000, timelineWeeks: [8, 12], adjustments: [], services: [], nextSteps: [], inclusions: [], exclusions: [] }] }), 'New pricing rule added.')
  return <section className="mt-8"><div className="flex flex-wrap items-center justify-between gap-4"><div><h2 className="text-2xl font-medium">Pricing rules</h2><p className="mt-2 text-sm text-muted">Set the eligible project, area band, and low/high rate per square foot.</p></div>{editable && <button className={buttonClass} type="button" onClick={addRule}>Add pricing rule</button>}</div>{!editable && <EditHint />}<div className="mt-6 grid gap-5">{card.rules.map((rule) => <RuleForm key={rule.id} rule={rule} card={card} editable={editable} onSave={saveRule} />)}</div></section>
}
function RuleForm({ rule, card, editable, onSave }) { const [values, setValues] = useState(rule); const set = (key, value) => setValues((current) => ({ ...current, [key]: value })); return <article className="rounded-lg border border-line bg-white p-5 sm:p-6"><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Field label="Project type"><select className={inputClass} disabled={!editable} value={values.projectCategory} onChange={(event) => set('projectCategory', event.target.value)}>{['New construction from scratch', 'Renovation of existing structure', 'Interior design only'].map((item) => <option key={item}>{item}</option>)}</select></Field><Field label="Property use"><select className={inputClass} disabled={!editable} value={values.propertyType} onChange={(event) => set('propertyType', event.target.value)}><option value="personal">Residential / personal</option><option value="commercial">Commercial</option></select></Field><Field label="Location"><select className={inputClass} disabled={!editable} value={values.zoneId} onChange={(event) => set('zoneId', event.target.value)}>{card.zones.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></Field><Field label="Finish level"><select className={inputClass} disabled={!editable} value={values.finishLevelId} onChange={(event) => set('finishLevelId', event.target.value)}>{card.finishes.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></Field><Field label="Minimum area (sq ft)"><input className={inputClass} disabled={!editable} type="number" min="1" value={values.minAreaSqFt} onChange={(event) => set('minAreaSqFt', Number(event.target.value))} /></Field><Field label="Maximum area (sq ft)"><input className={inputClass} disabled={!editable} type="number" min="1" value={values.maxAreaSqFt} onChange={(event) => set('maxAreaSqFt', Number(event.target.value))} /></Field><Field label="Lowest rate (₹ / sq ft)"><input className={inputClass} disabled={!editable} type="number" min="0" value={Math.round(values.lowRatePaisePerSqFt / 100)} onChange={(event) => set('lowRatePaisePerSqFt', Number(event.target.value) * 100)} /></Field><Field label="Highest rate (₹ / sq ft)"><input className={inputClass} disabled={!editable} type="number" min="0" value={Math.round(values.highRatePaisePerSqFt / 100)} onChange={(event) => set('highRatePaisePerSqFt', Number(event.target.value) * 100)} /></Field></div>{editable && <button className={`${buttonClass} mt-5`} type="button" onClick={() => onSave(values)}>Save this rule</button>}</article> }

function SimpleEditor({ type, card, editable, onUpdate }) { if (!card) return <EditHint />; const key = type === 'zone' ? 'zones' : 'finishes'; const title = type === 'zone' ? 'Project locations' : 'Finish levels'; const add = () => onUpdate((draft) => ({ ...draft, [key]: [...draft[key], { id: `${type}-${Date.now()}`, name: type === 'zone' ? 'New location' : 'New finish level', multiplier: 1, description: '' }] }), `${title.slice(0, -1)} added.`); const save = (item) => onUpdate((draft) => ({ ...draft, [key]: draft[key].map((current) => current.id === item.id ? item : current) }), `${title.slice(0, -1)} updated.`); return <section className="mt-8"><div className="flex flex-wrap items-center justify-between gap-4"><div><h2 className="text-2xl font-medium">{title}</h2><p className="mt-2 text-sm text-muted">A multiplier adjusts the matching base rule. Use 1 for no adjustment.</p></div>{editable && <button className={buttonClass} type="button" onClick={add}>Add {type === 'zone' ? 'location' : 'finish level'}</button>}</div>{!editable && <EditHint />}<div className="mt-6 grid gap-4 md:grid-cols-2">{card[key].map((item) => <SimpleCard key={item.id} item={item} editable={editable} onSave={save} />)}</div></section> }
function SimpleCard({ item, editable, onSave }) { const [values, setValues] = useState(item); return <article className="rounded-lg border border-line bg-white p-5"><div className="grid gap-4"><Field label="Name"><input className={inputClass} disabled={!editable} value={values.name} onChange={(event) => setValues({ ...values, name: event.target.value })} /></Field><Field label="Price multiplier"><input className={inputClass} disabled={!editable} type="number" min="0" step="0.01" value={values.multiplier} onChange={(event) => setValues({ ...values, multiplier: Number(event.target.value) })} /></Field><Field label="Customer-facing description"><input className={inputClass} disabled={!editable} value={values.description || ''} onChange={(event) => setValues({ ...values, description: event.target.value })} /></Field></div>{editable && <button className={`${buttonClass} mt-5`} type="button" onClick={() => onSave(values)}>Save</button>}</article> }

function AddonsEditor({ card, editable, onUpdate }) { if (!card) return <EditHint />; const add = () => onUpdate((draft) => ({ ...draft, addons: [...draft.addons, { id: `addon-${Date.now()}`, name: 'New add-on', description: '', lowPricePaise: 0, highPricePaise: 0, eligibleCategories: ['New construction from scratch'], eligiblePropertyTypes: ['personal'] }] }), 'Add-on added.'); const save = (item) => onUpdate((draft) => ({ ...draft, addons: draft.addons.map((current) => current.id === item.id ? item : current) }), 'Add-on updated.'); return <section className="mt-8"><div className="flex flex-wrap items-center justify-between gap-4"><div><h2 className="text-2xl font-medium">Optional add-ons</h2><p className="mt-2 text-sm text-muted">Customers can select eligible upgrades and see the revised estimate immediately.</p></div>{editable && <button className={buttonClass} type="button" onClick={add}>Add upgrade</button>}</div>{!editable && <EditHint />}<div className="mt-6 grid gap-5 md:grid-cols-2">{card.addons.map((addon) => <AddonCard key={addon.id} addon={addon} editable={editable} onSave={save} />)}</div></section> }
function AddonCard({ addon, editable, onSave }) { const [values, setValues] = useState(addon); const set = (key, value) => setValues((current) => ({ ...current, [key]: value })); return <article className="rounded-lg border border-line bg-white p-5"><div className="grid gap-4"><Field label="Upgrade name"><input className={inputClass} disabled={!editable} value={values.name} onChange={(event) => set('name', event.target.value)} /></Field><Field label="Description"><input className={inputClass} disabled={!editable} value={values.description} onChange={(event) => set('description', event.target.value)} /></Field><Field label="Lowest price (₹)"><input className={inputClass} disabled={!editable} type="number" min="0" value={values.lowPricePaise / 100} onChange={(event) => set('lowPricePaise', Number(event.target.value) * 100)} /></Field><Field label="Highest price (₹)"><input className={inputClass} disabled={!editable} type="number" min="0" value={values.highPricePaise / 100} onChange={(event) => set('highPricePaise', Number(event.target.value) * 100)} /></Field><ListText label="Eligible project types" value={values.eligibleCategories} onChange={(value) => set('eligibleCategories', value)} /><ListText label="Eligible property uses" value={values.eligiblePropertyTypes} onChange={(value) => set('eligiblePropertyTypes', value)} /></div>{editable && <button className={`${buttonClass} mt-5`} type="button" onClick={() => onSave(values)}>Save upgrade</button>}</article> }

function TemplatesEditor({ templates, onSave }) { const [draftTemplates, setDraftTemplates] = useState(templates); const edit = (index, key, value) => setDraftTemplates((current) => current.map((item, itemIndex) => itemIndex === index ? { ...item, [key]: value } : item)); return <section className="mt-8"><h2 className="text-2xl font-medium">Customer quote templates</h2><p className="mt-2 text-sm text-muted">Control the services, next steps, inclusions, and exclusions customers see in their quote.</p><div className="mt-6 grid gap-5">{draftTemplates.map((template, index) => <article className="rounded-lg border border-line bg-white p-5" key={template.id}><Field label="Template title"><input className={inputClass} value={template.name} onChange={(event) => edit(index, 'name', event.target.value)} /></Field><div className="mt-4 grid gap-4 md:grid-cols-2"><ListText label="Recommended services" value={template.services} onChange={(value) => edit(index, 'services', value)} /><ListText label="Suggested next steps" value={template.nextSteps} onChange={(value) => edit(index, 'nextSteps', value)} /><ListText label="Scope inclusions" value={template.inclusions} onChange={(value) => edit(index, 'inclusions', value)} /><ListText label="Scope exclusions" value={template.exclusions} onChange={(value) => edit(index, 'exclusions', value)} /></div></article>)}</div><button className={`${buttonClass} mt-6`} type="button" onClick={() => onSave(draftTemplates)}>Save templates</button></section> }

function Preview({ card, isDraft }) { const sample = useMemo(() => ({ projectCategory: 'New construction from scratch', propertyType: 'personal', areaSqFt: 1000, pricingZone: card?.zones[0]?.id, finishLevel: card?.finishes[0]?.id, needsArchitectConsult: 'yes' }), [card]); const plan = card ? calculateQuote(sample, card, [], { allowDraft: true }) : null; return <section className="mt-8"><h2 className="text-2xl font-medium">Quote preview</h2><p className="mt-2 text-sm text-muted">Testing {isDraft ? 'your current draft' : 'the published card'} with a 1,000 sq ft personal new-construction project.</p><article className="mt-6 rounded-lg border border-line bg-white p-5 sm:p-6">{plan?.status === 'matched' ? <><p className="text-xs font-bold uppercase tracking-[0.14em] text-gold">Estimated range</p><p className="mt-3 text-3xl font-medium text-goldDeep">{formatInrRange(plan.totalPaise[0], plan.totalPaise[1])}</p><div className="mt-6 divide-y divide-line border-y border-line">{plan.lineItems.map((item) => <div className="flex flex-wrap justify-between gap-3 py-3 text-sm" key={item.label}><span>{item.label}</span><span className="font-medium">{formatInrRange(item.lowPaise, item.highPaise)}</span></div>)}</div></> : <p className="text-sm text-red-700">This sample does not match exactly one rule. Review your project type, location, finish level, and area bands.</p>}</article></section> }

export default Admin
